version: "3"
services:
  app:
    build: .
    ports:
      - "4000:80"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"
    command: redis-server --appendonly yes
